version: "3"
services:
  node-app:
    build: 
      context: .
      target: production
      args:
        - NODE_ENV="production"
    environment:
      - PORT=4000
      - NODE_ENV=production
    command: npm run start
  
